# Usage:
# make			# compile all binary
# make clen		# remove ALL binaries and objects
CC = g++

PROJECTNAME = 3_5


all: $(PROJECTNAME)

$(PROJECTNAME):
	$(CC) -o $(PROJECTNAME).exe main.cpp

run:
	$(PROJECTNAME).exe

clean:
	del $(PROJECTNAME).exe
